### ISSUE TITLE
ByBit USDT Perpetual

### ISSUE THREAD

**Issue by Nitradamus** [frankrap/bybit-api#2]
While trying out crex I noticed I couldn't subscribe to positions on my bybit USDT account. It seems that the endpoint for USDT is different than the inverse one, see: https://github.com/ccxt/ccxt/issues/6827

I get the following error:

 2020/07/31 20:25:55 SignedRequest: {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1596219955.502511","rate_limit_status":119,"rate_limit_reset_ms":1596219955501,"rate_limit":120}

I see in the debug log it doesn't include the /private/linear/position/list as discussed above:

https://api.bybit.com/v2/private/position/list?xxxxx

I tried using the following symbol/market combinations:

`
market := crx.Market{
		Symbol: "BTCUSDT",
	}
ws.SubscribePositions(market, func(positions []*crx.Position) {
		//log.Printf("%#v", positions)
		for _, v := range positions {
			fmt.Println("profit:", v.Profit)
			fmt.Println("avg price:", v.AvgPrice)
			fmt.Println("size", v.Size)
		}
	})`

`position, _ := ws.GetPositions("USDT")
		for _, v := range position {
			fmt.Println(v)
		}`

I looked around but couldnt find a place to fix this. Can you maybe help me out? Thanks!

**Comment by frankrap** [comment]
By contrast, this library currently does not support usdt currency pairs.

**Comment by frankrap** [comment]
Updated
